2024-03-05 18:37:52,064 INFO    MainThread:3384 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-03-05 18:37:52,066 INFO    MainThread:3384 [wandb_setup.py:_flush():76] Configure stats pid to 3384
2024-03-05 18:37:52,066 INFO    MainThread:3384 [wandb_setup.py:_flush():76] Loading settings from C:\Users\16979\.config\wandb\settings
2024-03-05 18:37:52,066 INFO    MainThread:3384 [wandb_setup.py:_flush():76] Loading settings from G:\My Drive\SI_630\Homeworks\Homework2 - Backup\wandb\settings
2024-03-05 18:37:52,066 INFO    MainThread:3384 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-03-05 18:37:52,067 INFO    MainThread:3384 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-03-05 18:37:52,067 INFO    MainThread:3384 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-03-05 18:37:52,069 INFO    MainThread:3384 [wandb_init.py:_log_setup():526] Logging user logs to G:\My Drive\SI_630\Homeworks\Homework2 - Backup\wandb\run-20240305_183751-7f0sl11h\logs\debug.log
2024-03-05 18:37:52,071 INFO    MainThread:3384 [wandb_init.py:_log_setup():527] Logging internal logs to G:\My Drive\SI_630\Homeworks\Homework2 - Backup\wandb\run-20240305_183751-7f0sl11h\logs\debug-internal.log
2024-03-05 18:37:52,071 INFO    MainThread:3384 [wandb_init.py:init():566] calling init triggers
2024-03-05 18:37:52,072 INFO    MainThread:3384 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {}
2024-03-05 18:37:52,072 INFO    MainThread:3384 [wandb_init.py:init():591] re-initializing run, found existing run on stack: vgc2lnv5
2024-03-05 18:37:52,075 INFO    MainThread:3384 [wandb_run.py:_finish():1970] finishing run yanzhuo/attention_classifier/vgc2lnv5
2024-03-05 18:37:52,075 INFO    MainThread:3384 [jupyter.py:save_history():445] not saving jupyter history
2024-03-05 18:37:52,076 INFO    MainThread:3384 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-03-05 18:37:52,076 INFO    MainThread:3384 [wandb_init.py:_jupyter_teardown():454] cleaning up jupyter logic
2024-03-05 18:37:52,076 INFO    MainThread:3384 [wandb_run.py:_atexit_cleanup():2210] got exitcode: 0
2024-03-05 18:37:52,080 INFO    MainThread:3384 [wandb_run.py:_restore():2193] restore
2024-03-05 18:37:52,080 INFO    MainThread:3384 [wandb_run.py:_restore():2199] restore done
2024-03-05 18:37:59,420 INFO    MainThread:3384 [wandb_run.py:_footer_history_summary_info():3866] rendering history
2024-03-05 18:37:59,421 INFO    MainThread:3384 [wandb_run.py:_footer_history_summary_info():3898] rendering summary
2024-03-05 18:37:59,447 INFO    MainThread:3384 [wandb_run.py:_footer_sync_info():3825] logging synced files
2024-03-05 18:37:59,869 INFO    MainThread:3384 [wandb_init.py:init():616] starting backend
2024-03-05 18:37:59,869 INFO    MainThread:3384 [wandb_init.py:init():620] setting up manager
2024-03-05 18:37:59,898 INFO    MainThread:3384 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2024-03-05 18:37:59,898 INFO    MainThread:3384 [wandb_init.py:init():628] backend started and connected
2024-03-05 18:37:59,950 INFO    MainThread:3384 [wandb_run.py:_label_probe_notebook():1295] probe notebook
2024-03-05 18:37:59,953 INFO    MainThread:3384 [wandb_run.py:_label_probe_notebook():1305] Unable to probe notebook: 'charmap' codec can't decode byte 0x81 in position 3806: character maps to <undefined>
2024-03-05 18:37:59,954 INFO    MainThread:3384 [wandb_init.py:init():720] updated telemetry
2024-03-05 18:38:00,022 INFO    MainThread:3384 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-03-05 18:38:00,980 INFO    MainThread:3384 [wandb_run.py:_on_init():2262] communicating current version
2024-03-05 18:38:01,347 INFO    MainThread:3384 [wandb_run.py:_on_init():2271] got version response 
2024-03-05 18:38:01,348 INFO    MainThread:3384 [wandb_init.py:init():804] starting run threads in backend
2024-03-05 18:38:01,558 INFO    MainThread:3384 [wandb_run.py:_console_start():2241] atexit reg
2024-03-05 18:38:01,559 INFO    MainThread:3384 [wandb_run.py:_redirect():2096] redirect: wrap_raw
2024-03-05 18:38:01,559 INFO    MainThread:3384 [wandb_run.py:_redirect():2161] Wrapping output streams.
2024-03-05 18:38:01,559 INFO    MainThread:3384 [wandb_run.py:_redirect():2186] Redirects installed.
2024-03-05 18:38:01,565 INFO    MainThread:3384 [wandb_init.py:init():847] run started, returning control to user process
2024-03-05 18:40:03,453 INFO    MainThread:3384 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-03-05 18:40:03,455 INFO    MainThread:3384 [wandb_setup.py:_flush():76] Configure stats pid to 3384
2024-03-05 18:40:03,455 INFO    MainThread:3384 [wandb_setup.py:_flush():76] Loading settings from C:\Users\16979\.config\wandb\settings
2024-03-05 18:40:03,455 INFO    MainThread:3384 [wandb_setup.py:_flush():76] Loading settings from G:\My Drive\SI_630\Homeworks\Homework2 - Backup\wandb\settings
2024-03-05 18:40:03,456 INFO    MainThread:3384 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-03-05 18:40:03,456 INFO    MainThread:3384 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-03-05 18:40:03,456 INFO    MainThread:3384 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-03-05 18:40:03,459 INFO    MainThread:3384 [wandb_init.py:_log_setup():526] Logging user logs to G:\My Drive\SI_630\Homeworks\Homework2 - Backup\wandb\run-20240305_184003-gud82w4m\logs\debug.log
2024-03-05 18:40:03,461 INFO    MainThread:3384 [wandb_init.py:_log_setup():527] Logging internal logs to G:\My Drive\SI_630\Homeworks\Homework2 - Backup\wandb\run-20240305_184003-gud82w4m\logs\debug-internal.log
2024-03-05 18:40:03,461 INFO    MainThread:3384 [wandb_init.py:_jupyter_setup():472] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x000002031CD8BE30>
2024-03-05 18:40:03,462 INFO    MainThread:3384 [wandb_init.py:init():566] calling init triggers
2024-03-05 18:40:03,462 INFO    MainThread:3384 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {}
2024-03-05 18:40:03,462 INFO    MainThread:3384 [wandb_init.py:init():591] re-initializing run, found existing run on stack: 7f0sl11h
2024-03-05 18:40:03,464 INFO    MainThread:3384 [wandb_run.py:_finish():1970] finishing run yanzhuo/attention_classifier/7f0sl11h
2024-03-05 18:40:03,464 INFO    MainThread:3384 [wandb_run.py:_atexit_cleanup():2210] got exitcode: 0
2024-03-05 18:40:03,467 INFO    MainThread:3384 [wandb_run.py:_restore():2193] restore
2024-03-05 18:40:03,468 INFO    MainThread:3384 [wandb_run.py:_restore():2199] restore done
2024-03-05 18:40:07,350 INFO    MainThread:3384 [wandb_run.py:_footer_history_summary_info():3866] rendering history
2024-03-05 18:40:07,351 INFO    MainThread:3384 [wandb_run.py:_footer_history_summary_info():3898] rendering summary
2024-03-05 18:40:07,394 INFO    MainThread:3384 [wandb_run.py:_footer_sync_info():3825] logging synced files
