2024-03-02 04:40:26,678 INFO    MainThread:4524 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-03-02 04:40:26,678 INFO    MainThread:4524 [wandb_setup.py:_flush():76] Configure stats pid to 4524
2024-03-02 04:40:26,693 INFO    MainThread:4524 [wandb_setup.py:_flush():76] Loading settings from C:\Users\16979\.config\wandb\settings
2024-03-02 04:40:26,693 INFO    MainThread:4524 [wandb_setup.py:_flush():76] Loading settings from G:\Œ“µƒ‘∆∂À”≤≈Ã\SI_630\Homeworks\Homework2\wandb\settings
2024-03-02 04:40:26,693 INFO    MainThread:4524 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-03-02 04:40:26,693 INFO    MainThread:4524 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-03-02 04:40:26,693 INFO    MainThread:4524 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-03-02 04:40:26,693 INFO    MainThread:4524 [wandb_init.py:_log_setup():526] Logging user logs to G:\Œ“µƒ‘∆∂À”≤≈Ã\SI_630\Homeworks\Homework2\wandb\run-20240302_044026-vz58sfoo\logs\debug.log
2024-03-02 04:40:26,693 INFO    MainThread:4524 [wandb_init.py:_log_setup():527] Logging internal logs to G:\Œ“µƒ‘∆∂À”≤≈Ã\SI_630\Homeworks\Homework2\wandb\run-20240302_044026-vz58sfoo\logs\debug-internal.log
2024-03-02 04:40:26,693 INFO    MainThread:4524 [wandb_init.py:init():566] calling init triggers
2024-03-02 04:40:26,693 INFO    MainThread:4524 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {}
2024-03-02 04:40:26,693 INFO    MainThread:4524 [wandb_init.py:init():591] re-initializing run, found existing run on stack: rygt1t4c
2024-03-02 04:40:26,693 INFO    MainThread:4524 [wandb_run.py:_finish():1970] finishing run yanzhuo/word2vec_project/rygt1t4c
2024-03-02 04:40:26,693 INFO    MainThread:4524 [jupyter.py:save_history():445] not saving jupyter history
2024-03-02 04:40:26,693 INFO    MainThread:4524 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-03-02 04:40:26,706 INFO    MainThread:4524 [wandb_init.py:_jupyter_teardown():454] cleaning up jupyter logic
2024-03-02 04:40:26,706 INFO    MainThread:4524 [wandb_run.py:_atexit_cleanup():2210] got exitcode: 0
2024-03-02 04:40:26,709 INFO    MainThread:4524 [wandb_run.py:_restore():2193] restore
2024-03-02 04:40:26,709 INFO    MainThread:4524 [wandb_run.py:_restore():2199] restore done
2024-03-02 04:40:34,548 INFO    MainThread:4524 [wandb_run.py:_footer_history_summary_info():3866] rendering history
2024-03-02 04:40:34,549 INFO    MainThread:4524 [wandb_run.py:_footer_history_summary_info():3898] rendering summary
2024-03-02 04:40:34,587 INFO    MainThread:4524 [wandb_run.py:_footer_sync_info():3825] logging synced files
2024-03-02 04:40:35,018 INFO    MainThread:4524 [wandb_init.py:init():616] starting backend
2024-03-02 04:40:35,018 INFO    MainThread:4524 [wandb_init.py:init():620] setting up manager
2024-03-02 04:40:35,074 INFO    MainThread:4524 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2024-03-02 04:40:35,077 INFO    MainThread:4524 [wandb_init.py:init():628] backend started and connected
2024-03-02 04:40:35,164 INFO    MainThread:4524 [wandb_run.py:_label_probe_notebook():1295] probe notebook
2024-03-02 04:40:35,168 INFO    MainThread:4524 [wandb_run.py:_label_probe_notebook():1305] Unable to probe notebook: 'gbk' codec can't decode byte 0xa2 in position 18512: illegal multibyte sequence
2024-03-02 04:40:35,168 INFO    MainThread:4524 [wandb_init.py:init():720] updated telemetry
2024-03-02 04:40:35,283 INFO    MainThread:4524 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-03-02 04:40:36,194 INFO    MainThread:4524 [wandb_run.py:_on_init():2262] communicating current version
2024-03-02 04:40:36,593 INFO    MainThread:4524 [wandb_run.py:_on_init():2271] got version response 
2024-03-02 04:40:36,593 INFO    MainThread:4524 [wandb_init.py:init():804] starting run threads in backend
2024-03-02 04:40:37,791 INFO    MainThread:4524 [wandb_run.py:_console_start():2241] atexit reg
2024-03-02 04:40:37,791 INFO    MainThread:4524 [wandb_run.py:_redirect():2096] redirect: wrap_raw
2024-03-02 04:40:37,791 INFO    MainThread:4524 [wandb_run.py:_redirect():2161] Wrapping output streams.
2024-03-02 04:40:37,791 INFO    MainThread:4524 [wandb_run.py:_redirect():2186] Redirects installed.
2024-03-02 04:40:37,806 INFO    MainThread:4524 [wandb_init.py:init():847] run started, returning control to user process
2024-03-02 04:40:37,806 INFO    MainThread:4524 [wandb_watch.py:watch():51] Watching
2024-03-02 04:46:31,846 INFO    MainThread:4524 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-03-02 04:46:31,846 INFO    MainThread:4524 [wandb_setup.py:_flush():76] Configure stats pid to 4524
2024-03-02 04:46:31,846 INFO    MainThread:4524 [wandb_setup.py:_flush():76] Loading settings from C:\Users\16979\.config\wandb\settings
2024-03-02 04:46:31,846 INFO    MainThread:4524 [wandb_setup.py:_flush():76] Loading settings from G:\Œ“µƒ‘∆∂À”≤≈Ã\SI_630\Homeworks\Homework2\wandb\settings
2024-03-02 04:46:31,846 INFO    MainThread:4524 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-03-02 04:46:31,846 INFO    MainThread:4524 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-03-02 04:46:31,846 INFO    MainThread:4524 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-03-02 04:46:31,861 INFO    MainThread:4524 [wandb_init.py:_log_setup():526] Logging user logs to G:\Œ“µƒ‘∆∂À”≤≈Ã\SI_630\Homeworks\Homework2\wandb\run-20240302_044631-c09yq82c\logs\debug.log
2024-03-02 04:46:31,865 INFO    MainThread:4524 [wandb_init.py:_log_setup():527] Logging internal logs to G:\Œ“µƒ‘∆∂À”≤≈Ã\SI_630\Homeworks\Homework2\wandb\run-20240302_044631-c09yq82c\logs\debug-internal.log
2024-03-02 04:46:31,865 INFO    MainThread:4524 [wandb_init.py:_jupyter_setup():472] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x000002A2F095BD10>
2024-03-02 04:46:31,865 INFO    MainThread:4524 [wandb_init.py:init():566] calling init triggers
2024-03-02 04:46:31,865 INFO    MainThread:4524 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {}
2024-03-02 04:46:31,865 INFO    MainThread:4524 [wandb_init.py:init():591] re-initializing run, found existing run on stack: vz58sfoo
2024-03-02 04:46:31,873 INFO    MainThread:4524 [wandb_run.py:_finish():1970] finishing run yanzhuo/word2vec_project/vz58sfoo
2024-03-02 04:46:31,874 INFO    MainThread:4524 [wandb_run.py:_atexit_cleanup():2210] got exitcode: 0
2024-03-02 04:46:31,877 INFO    MainThread:4524 [wandb_run.py:_restore():2193] restore
2024-03-02 04:46:31,878 INFO    MainThread:4524 [wandb_run.py:_restore():2199] restore done
2024-03-02 04:46:38,603 INFO    MainThread:4524 [wandb_run.py:_footer_history_summary_info():3866] rendering history
2024-03-02 04:46:38,603 INFO    MainThread:4524 [wandb_run.py:_footer_history_summary_info():3898] rendering summary
2024-03-02 04:46:38,640 INFO    MainThread:4524 [wandb_run.py:_footer_sync_info():3825] logging synced files
