2024-03-02 07:10:12,072 INFO    MainThread:3892 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-03-02 07:10:12,076 INFO    MainThread:3892 [wandb_setup.py:_flush():76] Configure stats pid to 3892
2024-03-02 07:10:12,076 INFO    MainThread:3892 [wandb_setup.py:_flush():76] Loading settings from C:\Users\16979\.config\wandb\settings
2024-03-02 07:10:12,076 INFO    MainThread:3892 [wandb_setup.py:_flush():76] Loading settings from G:\Œ“µƒ‘∆∂À”≤≈Ã\SI_630\Homeworks\Homework2\wandb\settings
2024-03-02 07:10:12,076 INFO    MainThread:3892 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-03-02 07:10:12,076 INFO    MainThread:3892 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-03-02 07:10:12,076 INFO    MainThread:3892 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-03-02 07:10:12,076 INFO    MainThread:3892 [wandb_init.py:_log_setup():526] Logging user logs to G:\Œ“µƒ‘∆∂À”≤≈Ã\SI_630\Homeworks\Homework2\wandb\run-20240302_071012-1fdmwc26\logs\debug.log
2024-03-02 07:10:12,080 INFO    MainThread:3892 [wandb_init.py:_log_setup():527] Logging internal logs to G:\Œ“µƒ‘∆∂À”≤≈Ã\SI_630\Homeworks\Homework2\wandb\run-20240302_071012-1fdmwc26\logs\debug-internal.log
2024-03-02 07:10:12,080 INFO    MainThread:3892 [wandb_init.py:_jupyter_setup():472] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x00000173DD1BBDD0>
2024-03-02 07:10:12,080 INFO    MainThread:3892 [wandb_init.py:init():566] calling init triggers
2024-03-02 07:10:12,080 INFO    MainThread:3892 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {}
2024-03-02 07:10:12,080 INFO    MainThread:3892 [wandb_init.py:init():616] starting backend
2024-03-02 07:10:12,080 INFO    MainThread:3892 [wandb_init.py:init():620] setting up manager
2024-03-02 07:10:12,124 INFO    MainThread:3892 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2024-03-02 07:10:12,124 INFO    MainThread:3892 [wandb_init.py:init():628] backend started and connected
2024-03-02 07:10:12,217 INFO    MainThread:3892 [wandb_run.py:_label_probe_notebook():1295] probe notebook
2024-03-02 07:10:12,221 INFO    MainThread:3892 [wandb_run.py:_label_probe_notebook():1305] Unable to probe notebook: 'gbk' codec can't decode byte 0xae in position 3686: illegal multibyte sequence
2024-03-02 07:10:12,221 INFO    MainThread:3892 [wandb_init.py:init():720] updated telemetry
2024-03-02 07:10:12,361 INFO    MainThread:3892 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-03-02 07:10:12,975 INFO    MainThread:3892 [wandb_run.py:_on_init():2262] communicating current version
2024-03-02 07:10:13,406 INFO    MainThread:3892 [wandb_run.py:_on_init():2271] got version response 
2024-03-02 07:10:13,406 INFO    MainThread:3892 [wandb_init.py:init():804] starting run threads in backend
2024-03-02 07:10:14,441 INFO    MainThread:3892 [wandb_run.py:_console_start():2241] atexit reg
2024-03-02 07:10:14,441 INFO    MainThread:3892 [wandb_run.py:_redirect():2096] redirect: wrap_raw
2024-03-02 07:10:14,445 INFO    MainThread:3892 [wandb_run.py:_redirect():2161] Wrapping output streams.
2024-03-02 07:10:14,445 INFO    MainThread:3892 [wandb_run.py:_redirect():2186] Redirects installed.
2024-03-02 07:10:14,449 INFO    MainThread:3892 [wandb_init.py:init():847] run started, returning control to user process
2024-03-02 07:10:25,921 INFO    MainThread:3892 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-03-02 07:10:25,921 INFO    MainThread:3892 [wandb_init.py:_pause_backend():437] pausing backend
2024-03-02 07:10:25,928 INFO    MainThread:3892 [wandb_init.py:_resume_backend():442] resuming backend
2024-03-02 07:10:28,066 INFO    MainThread:3892 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-03-02 07:10:28,066 INFO    MainThread:3892 [wandb_init.py:_pause_backend():437] pausing backend
2024-03-02 07:10:28,075 INFO    MainThread:3892 [wandb_init.py:_resume_backend():442] resuming backend
2024-03-02 07:10:28,179 INFO    MainThread:3892 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-03-02 07:10:28,191 INFO    MainThread:3892 [wandb_setup.py:_flush():76] Configure stats pid to 3892
2024-03-02 07:10:28,199 INFO    MainThread:3892 [wandb_setup.py:_flush():76] Loading settings from C:\Users\16979\.config\wandb\settings
2024-03-02 07:10:28,203 INFO    MainThread:3892 [wandb_setup.py:_flush():76] Loading settings from G:\Œ“µƒ‘∆∂À”≤≈Ã\SI_630\Homeworks\Homework2\wandb\settings
2024-03-02 07:10:28,203 INFO    MainThread:3892 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-03-02 07:10:28,204 INFO    MainThread:3892 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-03-02 07:10:28,204 INFO    MainThread:3892 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-03-02 07:10:28,204 INFO    MainThread:3892 [wandb_init.py:_log_setup():526] Logging user logs to G:\Œ“µƒ‘∆∂À”≤≈Ã\SI_630\Homeworks\Homework2\wandb\run-20240302_071028-gy0m8611\logs\debug.log
2024-03-02 07:10:28,208 INFO    MainThread:3892 [wandb_init.py:_log_setup():527] Logging internal logs to G:\Œ“µƒ‘∆∂À”≤≈Ã\SI_630\Homeworks\Homework2\wandb\run-20240302_071028-gy0m8611\logs\debug-internal.log
2024-03-02 07:10:28,208 INFO    MainThread:3892 [wandb_init.py:init():566] calling init triggers
2024-03-02 07:10:28,208 INFO    MainThread:3892 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {}
2024-03-02 07:10:28,208 INFO    MainThread:3892 [wandb_init.py:init():591] re-initializing run, found existing run on stack: 1fdmwc26
2024-03-02 07:10:28,212 INFO    MainThread:3892 [wandb_run.py:_finish():1970] finishing run yanzhuo/attention_classifier/1fdmwc26
2024-03-02 07:10:28,212 INFO    MainThread:3892 [jupyter.py:save_history():445] not saving jupyter history
2024-03-02 07:10:28,212 INFO    MainThread:3892 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-03-02 07:10:28,212 INFO    MainThread:3892 [wandb_init.py:_jupyter_teardown():454] cleaning up jupyter logic
2024-03-02 07:10:28,212 INFO    MainThread:3892 [wandb_run.py:_atexit_cleanup():2210] got exitcode: 0
2024-03-02 07:10:28,216 INFO    MainThread:3892 [wandb_run.py:_restore():2193] restore
2024-03-02 07:10:28,218 INFO    MainThread:3892 [wandb_run.py:_restore():2199] restore done
2024-03-02 07:10:32,566 INFO    MainThread:3892 [wandb_run.py:_footer_history_summary_info():3866] rendering history
2024-03-02 07:10:32,567 INFO    MainThread:3892 [wandb_run.py:_footer_history_summary_info():3898] rendering summary
2024-03-02 07:10:32,605 INFO    MainThread:3892 [wandb_run.py:_footer_sync_info():3825] logging synced files
