2024-03-04 17:08:57,713 INFO    MainThread:3340 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-03-04 17:08:57,717 INFO    MainThread:3340 [wandb_setup.py:_flush():76] Configure stats pid to 3340
2024-03-04 17:08:57,719 INFO    MainThread:3340 [wandb_setup.py:_flush():76] Loading settings from C:\Users\16979\.config\wandb\settings
2024-03-04 17:08:57,720 INFO    MainThread:3340 [wandb_setup.py:_flush():76] Loading settings from G:\My Drive\SI_630\Homeworks\Homework2 - Backup\wandb\settings
2024-03-04 17:08:57,720 INFO    MainThread:3340 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-03-04 17:08:57,721 INFO    MainThread:3340 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-03-04 17:08:57,721 INFO    MainThread:3340 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-03-04 17:08:57,724 INFO    MainThread:3340 [wandb_init.py:_log_setup():526] Logging user logs to G:\My Drive\SI_630\Homeworks\Homework2 - Backup\wandb\run-20240304_170857-drbcy1qu\logs\debug.log
2024-03-04 17:08:57,728 INFO    MainThread:3340 [wandb_init.py:_log_setup():527] Logging internal logs to G:\My Drive\SI_630\Homeworks\Homework2 - Backup\wandb\run-20240304_170857-drbcy1qu\logs\debug-internal.log
2024-03-04 17:08:57,729 INFO    MainThread:3340 [wandb_init.py:_jupyter_setup():472] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x000001DFDDD56360>
2024-03-04 17:08:57,729 INFO    MainThread:3340 [wandb_init.py:init():566] calling init triggers
2024-03-04 17:08:57,729 INFO    MainThread:3340 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {}
2024-03-04 17:08:57,729 INFO    MainThread:3340 [wandb_init.py:init():591] re-initializing run, found existing run on stack: 5nasvdcs
2024-03-04 17:08:57,733 INFO    MainThread:3340 [wandb_run.py:_finish():1970] finishing run yanzhuo/attention_classifier/5nasvdcs
2024-03-04 17:08:57,733 INFO    MainThread:3340 [wandb_run.py:_atexit_cleanup():2210] got exitcode: 0
2024-03-04 17:08:57,736 INFO    MainThread:3340 [wandb_run.py:_restore():2193] restore
2024-03-04 17:08:57,736 INFO    MainThread:3340 [wandb_run.py:_restore():2199] restore done
2024-03-04 17:09:01,106 INFO    MainThread:3340 [wandb_run.py:_footer_history_summary_info():3866] rendering history
2024-03-04 17:09:01,107 INFO    MainThread:3340 [wandb_run.py:_footer_history_summary_info():3898] rendering summary
2024-03-04 17:09:01,133 INFO    MainThread:3340 [wandb_run.py:_footer_sync_info():3825] logging synced files
2024-03-04 17:09:01,176 INFO    MainThread:3340 [wandb_init.py:init():616] starting backend
2024-03-04 17:09:01,176 INFO    MainThread:3340 [wandb_init.py:init():620] setting up manager
2024-03-04 17:09:01,223 INFO    MainThread:3340 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2024-03-04 17:09:01,224 INFO    MainThread:3340 [wandb_init.py:init():628] backend started and connected
2024-03-04 17:09:01,296 INFO    MainThread:3340 [wandb_run.py:_label_probe_notebook():1295] probe notebook
2024-03-04 17:09:01,301 INFO    MainThread:3340 [wandb_run.py:_label_probe_notebook():1305] Unable to probe notebook: 'charmap' codec can't decode byte 0x81 in position 3796: character maps to <undefined>
2024-03-04 17:09:01,301 INFO    MainThread:3340 [wandb_init.py:init():720] updated telemetry
2024-03-04 17:09:01,424 INFO    MainThread:3340 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-03-04 17:09:02,654 INFO    MainThread:3340 [wandb_run.py:_on_init():2262] communicating current version
2024-03-04 17:09:02,911 INFO    MainThread:3340 [wandb_run.py:_on_init():2271] got version response 
2024-03-04 17:09:02,912 INFO    MainThread:3340 [wandb_init.py:init():804] starting run threads in backend
2024-03-04 17:09:03,205 INFO    MainThread:3340 [wandb_run.py:_console_start():2241] atexit reg
2024-03-04 17:09:03,206 INFO    MainThread:3340 [wandb_run.py:_redirect():2096] redirect: wrap_raw
2024-03-04 17:09:03,207 INFO    MainThread:3340 [wandb_run.py:_redirect():2161] Wrapping output streams.
2024-03-04 17:09:03,207 INFO    MainThread:3340 [wandb_run.py:_redirect():2186] Redirects installed.
2024-03-04 17:09:03,220 INFO    MainThread:3340 [wandb_init.py:init():847] run started, returning control to user process
2024-03-04 17:14:34,255 INFO    MainThread:3340 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-03-04 17:14:34,255 INFO    MainThread:3340 [wandb_init.py:_pause_backend():437] pausing backend
2024-03-04 17:14:59,287 INFO    MainThread:3340 [wandb_init.py:_resume_backend():442] resuming backend
2024-03-04 17:15:00,628 INFO    MainThread:3340 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-03-04 17:15:00,628 INFO    MainThread:3340 [wandb_init.py:_pause_backend():437] pausing backend
2024-03-04 17:15:04,385 INFO    MainThread:3340 [wandb_init.py:_resume_backend():442] resuming backend
2024-03-04 17:15:04,471 INFO    MainThread:3340 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-03-04 17:15:04,474 INFO    MainThread:3340 [wandb_setup.py:_flush():76] Configure stats pid to 3340
2024-03-04 17:15:04,474 INFO    MainThread:3340 [wandb_setup.py:_flush():76] Loading settings from C:\Users\16979\.config\wandb\settings
2024-03-04 17:15:04,474 INFO    MainThread:3340 [wandb_setup.py:_flush():76] Loading settings from G:\My Drive\SI_630\Homeworks\Homework2 - Backup\wandb\settings
2024-03-04 17:15:04,474 INFO    MainThread:3340 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-03-04 17:15:04,475 INFO    MainThread:3340 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-03-04 17:15:04,475 INFO    MainThread:3340 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-03-04 17:15:04,477 INFO    MainThread:3340 [wandb_init.py:_log_setup():526] Logging user logs to G:\My Drive\SI_630\Homeworks\Homework2 - Backup\wandb\run-20240304_171504-nqigzcsv\logs\debug.log
2024-03-04 17:15:04,479 INFO    MainThread:3340 [wandb_init.py:_log_setup():527] Logging internal logs to G:\My Drive\SI_630\Homeworks\Homework2 - Backup\wandb\run-20240304_171504-nqigzcsv\logs\debug-internal.log
2024-03-04 17:15:04,479 INFO    MainThread:3340 [wandb_init.py:init():566] calling init triggers
2024-03-04 17:15:04,480 INFO    MainThread:3340 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {}
2024-03-04 17:15:04,480 INFO    MainThread:3340 [wandb_init.py:init():591] re-initializing run, found existing run on stack: drbcy1qu
2024-03-04 17:15:04,482 INFO    MainThread:3340 [wandb_run.py:_finish():1970] finishing run yanzhuo/attention_classifier/drbcy1qu
2024-03-04 17:15:04,482 INFO    MainThread:3340 [jupyter.py:save_history():445] not saving jupyter history
2024-03-04 17:15:04,483 INFO    MainThread:3340 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-03-04 17:15:04,483 INFO    MainThread:3340 [wandb_init.py:_jupyter_teardown():454] cleaning up jupyter logic
2024-03-04 17:15:04,483 INFO    MainThread:3340 [wandb_run.py:_atexit_cleanup():2210] got exitcode: 0
2024-03-04 17:15:04,486 INFO    MainThread:3340 [wandb_run.py:_restore():2193] restore
2024-03-04 17:15:04,486 INFO    MainThread:3340 [wandb_run.py:_restore():2199] restore done
2024-03-04 17:15:09,051 INFO    MainThread:3340 [wandb_run.py:_footer_history_summary_info():3866] rendering history
2024-03-04 17:15:09,052 INFO    MainThread:3340 [wandb_run.py:_footer_history_summary_info():3898] rendering summary
2024-03-04 17:15:09,085 INFO    MainThread:3340 [wandb_run.py:_footer_sync_info():3825] logging synced files
