2024-03-05 06:22:30,292 INFO    MainThread:25648 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-03-05 06:22:30,294 INFO    MainThread:25648 [wandb_setup.py:_flush():76] Configure stats pid to 25648
2024-03-05 06:22:30,294 INFO    MainThread:25648 [wandb_setup.py:_flush():76] Loading settings from C:\Users\16979\.config\wandb\settings
2024-03-05 06:22:30,294 INFO    MainThread:25648 [wandb_setup.py:_flush():76] Loading settings from G:\My Drive\SI_630\Homeworks\Homework2 - Backup\wandb\settings
2024-03-05 06:22:30,294 INFO    MainThread:25648 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-03-05 06:22:30,294 INFO    MainThread:25648 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-03-05 06:22:30,295 INFO    MainThread:25648 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-03-05 06:22:30,298 INFO    MainThread:25648 [wandb_init.py:_log_setup():526] Logging user logs to G:\My Drive\SI_630\Homeworks\Homework2 - Backup\wandb\run-20240305_062230-nv4bbngy\logs\debug.log
2024-03-05 06:22:30,301 INFO    MainThread:25648 [wandb_init.py:_log_setup():527] Logging internal logs to G:\My Drive\SI_630\Homeworks\Homework2 - Backup\wandb\run-20240305_062230-nv4bbngy\logs\debug-internal.log
2024-03-05 06:22:30,301 INFO    MainThread:25648 [wandb_init.py:init():566] calling init triggers
2024-03-05 06:22:30,302 INFO    MainThread:25648 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {}
2024-03-05 06:22:30,302 INFO    MainThread:25648 [wandb_init.py:init():591] re-initializing run, found existing run on stack: bau4yut5
2024-03-05 06:22:30,304 INFO    MainThread:25648 [wandb_run.py:_finish():1970] finishing run yanzhuo/attention_classifier2/bau4yut5
2024-03-05 06:22:30,304 INFO    MainThread:25648 [jupyter.py:save_history():445] not saving jupyter history
2024-03-05 06:22:30,304 INFO    MainThread:25648 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-03-05 06:22:30,306 INFO    MainThread:25648 [wandb_init.py:_jupyter_teardown():454] cleaning up jupyter logic
2024-03-05 06:22:30,306 INFO    MainThread:25648 [wandb_run.py:_atexit_cleanup():2210] got exitcode: 0
2024-03-05 06:22:30,310 INFO    MainThread:25648 [wandb_run.py:_restore():2193] restore
2024-03-05 06:22:30,310 INFO    MainThread:25648 [wandb_run.py:_restore():2199] restore done
2024-03-05 06:22:34,680 INFO    MainThread:25648 [wandb_run.py:_footer_history_summary_info():3866] rendering history
2024-03-05 06:22:34,680 INFO    MainThread:25648 [wandb_run.py:_footer_history_summary_info():3898] rendering summary
2024-03-05 06:22:34,714 INFO    MainThread:25648 [wandb_run.py:_footer_sync_info():3825] logging synced files
2024-03-05 06:22:34,770 INFO    MainThread:25648 [wandb_init.py:init():616] starting backend
2024-03-05 06:22:34,770 INFO    MainThread:25648 [wandb_init.py:init():620] setting up manager
2024-03-05 06:22:34,818 INFO    MainThread:25648 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2024-03-05 06:22:34,821 INFO    MainThread:25648 [wandb_init.py:init():628] backend started and connected
2024-03-05 06:22:34,899 INFO    MainThread:25648 [wandb_run.py:_label_probe_notebook():1295] probe notebook
2024-03-05 06:22:34,904 INFO    MainThread:25648 [wandb_run.py:_label_probe_notebook():1305] Unable to probe notebook: 'charmap' codec can't decode byte 0x81 in position 3806: character maps to <undefined>
2024-03-05 06:22:34,905 INFO    MainThread:25648 [wandb_init.py:init():720] updated telemetry
2024-03-05 06:22:35,024 INFO    MainThread:25648 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-03-05 06:22:36,302 INFO    MainThread:25648 [wandb_run.py:_on_init():2262] communicating current version
2024-03-05 06:22:36,722 INFO    MainThread:25648 [wandb_run.py:_on_init():2271] got version response 
2024-03-05 06:22:36,722 INFO    MainThread:25648 [wandb_init.py:init():804] starting run threads in backend
2024-03-05 06:22:37,020 INFO    MainThread:25648 [wandb_run.py:_console_start():2241] atexit reg
2024-03-05 06:22:37,020 INFO    MainThread:25648 [wandb_run.py:_redirect():2096] redirect: wrap_raw
2024-03-05 06:22:37,023 INFO    MainThread:25648 [wandb_run.py:_redirect():2161] Wrapping output streams.
2024-03-05 06:22:37,023 INFO    MainThread:25648 [wandb_run.py:_redirect():2186] Redirects installed.
2024-03-05 06:22:37,031 INFO    MainThread:25648 [wandb_init.py:init():847] run started, returning control to user process
2024-03-05 06:22:56,138 INFO    MainThread:25648 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-03-05 06:22:56,142 INFO    MainThread:25648 [wandb_setup.py:_flush():76] Configure stats pid to 25648
2024-03-05 06:22:56,143 INFO    MainThread:25648 [wandb_setup.py:_flush():76] Loading settings from C:\Users\16979\.config\wandb\settings
2024-03-05 06:22:56,143 INFO    MainThread:25648 [wandb_setup.py:_flush():76] Loading settings from G:\My Drive\SI_630\Homeworks\Homework2 - Backup\wandb\settings
2024-03-05 06:22:56,143 INFO    MainThread:25648 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-03-05 06:22:56,144 INFO    MainThread:25648 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-03-05 06:22:56,144 INFO    MainThread:25648 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-03-05 06:22:56,147 INFO    MainThread:25648 [wandb_init.py:_log_setup():526] Logging user logs to G:\My Drive\SI_630\Homeworks\Homework2 - Backup\wandb\run-20240305_062256-10tx22e7\logs\debug.log
2024-03-05 06:22:56,149 INFO    MainThread:25648 [wandb_init.py:_log_setup():527] Logging internal logs to G:\My Drive\SI_630\Homeworks\Homework2 - Backup\wandb\run-20240305_062256-10tx22e7\logs\debug-internal.log
2024-03-05 06:22:56,149 INFO    MainThread:25648 [wandb_init.py:_jupyter_setup():472] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x000002022D6461B0>
2024-03-05 06:22:56,150 INFO    MainThread:25648 [wandb_init.py:init():566] calling init triggers
2024-03-05 06:22:56,150 INFO    MainThread:25648 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {}
2024-03-05 06:22:56,150 INFO    MainThread:25648 [wandb_init.py:init():591] re-initializing run, found existing run on stack: nv4bbngy
2024-03-05 06:22:56,154 INFO    MainThread:25648 [wandb_run.py:_finish():1970] finishing run yanzhuo/attention_classifier2/nv4bbngy
2024-03-05 06:22:56,154 INFO    MainThread:25648 [wandb_run.py:_atexit_cleanup():2210] got exitcode: 0
2024-03-05 06:22:56,157 INFO    MainThread:25648 [wandb_run.py:_restore():2193] restore
2024-03-05 06:22:56,158 INFO    MainThread:25648 [wandb_run.py:_restore():2199] restore done
2024-03-05 06:23:00,933 INFO    MainThread:25648 [wandb_run.py:_footer_history_summary_info():3866] rendering history
2024-03-05 06:23:00,935 INFO    MainThread:25648 [wandb_run.py:_footer_history_summary_info():3898] rendering summary
2024-03-05 06:23:00,963 INFO    MainThread:25648 [wandb_run.py:_footer_sync_info():3825] logging synced files
