2024-03-05 12:54:05,075 INFO    MainThread:35160 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-03-05 12:54:05,077 INFO    MainThread:35160 [wandb_setup.py:_flush():76] Configure stats pid to 35160
2024-03-05 12:54:05,077 INFO    MainThread:35160 [wandb_setup.py:_flush():76] Loading settings from C:\Users\16979\.config\wandb\settings
2024-03-05 12:54:05,077 INFO    MainThread:35160 [wandb_setup.py:_flush():76] Loading settings from G:\My Drive\SI_630\Homeworks\Homework2 - Backup\wandb\settings
2024-03-05 12:54:05,077 INFO    MainThread:35160 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-03-05 12:54:05,078 INFO    MainThread:35160 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-03-05 12:54:05,078 INFO    MainThread:35160 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-03-05 12:54:05,080 INFO    MainThread:35160 [wandb_init.py:_log_setup():526] Logging user logs to G:\My Drive\SI_630\Homeworks\Homework2 - Backup\wandb\run-20240305_125405-iay4cqzi\logs\debug.log
2024-03-05 12:54:05,082 INFO    MainThread:35160 [wandb_init.py:_log_setup():527] Logging internal logs to G:\My Drive\SI_630\Homeworks\Homework2 - Backup\wandb\run-20240305_125405-iay4cqzi\logs\debug-internal.log
2024-03-05 12:54:05,082 INFO    MainThread:35160 [wandb_init.py:_jupyter_setup():472] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x000001D36598A5A0>
2024-03-05 12:54:05,083 INFO    MainThread:35160 [wandb_init.py:init():566] calling init triggers
2024-03-05 12:54:05,083 INFO    MainThread:35160 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {}
2024-03-05 12:54:05,083 INFO    MainThread:35160 [wandb_init.py:init():616] starting backend
2024-03-05 12:54:05,083 INFO    MainThread:35160 [wandb_init.py:init():620] setting up manager
2024-03-05 12:54:05,110 INFO    MainThread:35160 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2024-03-05 12:54:05,112 INFO    MainThread:35160 [wandb_init.py:init():628] backend started and connected
2024-03-05 12:54:05,175 INFO    MainThread:35160 [wandb_run.py:_label_probe_notebook():1295] probe notebook
2024-03-05 12:54:05,178 INFO    MainThread:35160 [wandb_run.py:_label_probe_notebook():1305] Unable to probe notebook: 'charmap' codec can't decode byte 0x81 in position 3806: character maps to <undefined>
2024-03-05 12:54:05,179 INFO    MainThread:35160 [wandb_init.py:init():720] updated telemetry
2024-03-05 12:54:05,283 INFO    MainThread:35160 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-03-05 12:54:05,834 INFO    MainThread:35160 [wandb_run.py:_on_init():2262] communicating current version
2024-03-05 12:54:06,245 INFO    MainThread:35160 [wandb_run.py:_on_init():2271] got version response 
2024-03-05 12:54:06,246 INFO    MainThread:35160 [wandb_init.py:init():804] starting run threads in backend
2024-03-05 12:54:06,655 INFO    MainThread:35160 [wandb_run.py:_console_start():2241] atexit reg
2024-03-05 12:54:06,655 INFO    MainThread:35160 [wandb_run.py:_redirect():2096] redirect: wrap_raw
2024-03-05 12:54:06,658 INFO    MainThread:35160 [wandb_run.py:_redirect():2161] Wrapping output streams.
2024-03-05 12:54:06,658 INFO    MainThread:35160 [wandb_run.py:_redirect():2186] Redirects installed.
2024-03-05 12:54:06,671 INFO    MainThread:35160 [wandb_init.py:init():847] run started, returning control to user process
2024-03-05 12:54:06,672 INFO    MainThread:35160 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-03-05 12:54:06,672 INFO    MainThread:35160 [wandb_init.py:_pause_backend():437] pausing backend
2024-03-05 12:54:06,678 INFO    MainThread:35160 [wandb_init.py:_resume_backend():442] resuming backend
2024-03-05 13:10:12,434 INFO    MainThread:35160 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-03-05 13:10:12,435 INFO    MainThread:35160 [wandb_init.py:_pause_backend():437] pausing backend
2024-03-05 13:10:12,438 INFO    MainThread:35160 [wandb_init.py:_resume_backend():442] resuming backend
2024-03-05 13:10:13,394 INFO    MainThread:35160 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-03-05 13:10:13,394 INFO    MainThread:35160 [wandb_init.py:_pause_backend():437] pausing backend
2024-03-05 13:10:13,398 INFO    MainThread:35160 [wandb_init.py:_resume_backend():442] resuming backend
2024-03-05 13:10:13,471 INFO    MainThread:35160 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-03-05 13:10:13,472 INFO    MainThread:35160 [wandb_setup.py:_flush():76] Configure stats pid to 35160
2024-03-05 13:10:13,473 INFO    MainThread:35160 [wandb_setup.py:_flush():76] Loading settings from C:\Users\16979\.config\wandb\settings
2024-03-05 13:10:13,473 INFO    MainThread:35160 [wandb_setup.py:_flush():76] Loading settings from G:\My Drive\SI_630\Homeworks\Homework2 - Backup\wandb\settings
2024-03-05 13:10:13,473 INFO    MainThread:35160 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-03-05 13:10:13,473 INFO    MainThread:35160 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-03-05 13:10:13,474 INFO    MainThread:35160 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-03-05 13:10:13,475 INFO    MainThread:35160 [wandb_init.py:_log_setup():526] Logging user logs to G:\My Drive\SI_630\Homeworks\Homework2 - Backup\wandb\run-20240305_131013-8bciandm\logs\debug.log
2024-03-05 13:10:13,476 INFO    MainThread:35160 [wandb_init.py:_log_setup():527] Logging internal logs to G:\My Drive\SI_630\Homeworks\Homework2 - Backup\wandb\run-20240305_131013-8bciandm\logs\debug-internal.log
2024-03-05 13:10:13,477 INFO    MainThread:35160 [wandb_init.py:init():566] calling init triggers
2024-03-05 13:10:13,477 INFO    MainThread:35160 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {}
2024-03-05 13:10:13,478 INFO    MainThread:35160 [wandb_init.py:init():591] re-initializing run, found existing run on stack: iay4cqzi
2024-03-05 13:10:13,479 INFO    MainThread:35160 [wandb_run.py:_finish():1970] finishing run yanzhuo/attention_classifier/iay4cqzi
2024-03-05 13:10:13,480 INFO    MainThread:35160 [jupyter.py:save_history():445] not saving jupyter history
2024-03-05 13:10:13,480 INFO    MainThread:35160 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-03-05 13:10:13,480 INFO    MainThread:35160 [wandb_init.py:_jupyter_teardown():454] cleaning up jupyter logic
2024-03-05 13:10:13,480 INFO    MainThread:35160 [wandb_run.py:_atexit_cleanup():2210] got exitcode: 0
2024-03-05 13:10:13,482 INFO    MainThread:35160 [wandb_run.py:_restore():2193] restore
2024-03-05 13:10:13,482 INFO    MainThread:35160 [wandb_run.py:_restore():2199] restore done
2024-03-05 13:10:18,975 INFO    MainThread:35160 [wandb_run.py:_footer_history_summary_info():3866] rendering history
2024-03-05 13:10:18,976 INFO    MainThread:35160 [wandb_run.py:_footer_history_summary_info():3898] rendering summary
2024-03-05 13:10:18,993 INFO    MainThread:35160 [wandb_run.py:_footer_sync_info():3825] logging synced files
